# The configurations that used for the recording, feel free to edit them
config:

  # Specify a command to be executed
  # like `/bin/bash -l`, `ls`, or any other commands
  # the default is bash for Linux
  # or powershell.exe for Windows
  command: bash -l

  # Specify the current working directory path
  # the default is the current working directory path
  cwd: /Users/gustavobazan

  # Export additional ENV variables
  env:
    recording: true

  # Explicitly set the number of columns
  # or use `auto` to take the current
  # number of columns of your shell
  cols: 110

  # Explicitly set the number of rows
  # or use `auto` to take the current
  # number of rows of your shell
  rows: 20

  # Amount of times to repeat GIF
  # If value is -1, play once
  # If value is 0, loop indefinitely
  # If value is a positive number, loop n times
  repeat: 0

  # Quality
  # 1 - 100
  quality: 100

  # Delay between frames in ms
  # If the value is `auto` use the actual recording delays
  frameDelay: auto

  # Maximum delay between frames in ms
  # Ignored if the `frameDelay` isn't set to `auto`
  # Set to `auto` to prevent limiting the max idle time
  maxIdleTime: 2000

  # The surrounding frame box
  # The `type` can be null, window, floating, or solid`
  # To hide the title use the value null
  # Don't forget to add a backgroundColor style with a null as type
  frameBox:
    type: floating
    title: MongoDB
    style:
      border: 0px black solid
      boxShadow: none
      margin: 0px

  # Add a watermark image to the rendered gif
  # You need to specify an absolute path for
  # the image on your machine or a URL, and you can also
  # add your own CSS styles
  watermark:
    imagePath: null
    style:
      position: absolute
      right: 15px
      bottom: 15px
      width: 100px
      opacity: 0.9

  # Cursor style can be one of
  # `block`, `underline`, or `bar`
  cursorStyle: block

  # Font family
  # You can use any font that is installed on your machine
  # in CSS-like syntax
  fontFamily: "Fira Mono, Monaco, Lucida Console, Ubuntu Mono, Monospace"

  # The size of the font
  fontSize: 20

  # The height of lines
  lineHeight: 1

  # The spacing between letters
  letterSpacing: 0

  # Theme
  theme:
    background: "transparent"
    foreground: "#afafaf"
    cursor: "#c7c7c7"
    black: "#232628"
    red: "#fc4384"
    green: "#b3e33b"
    yellow: "#ffa727"
    blue: "#75dff2"
    magenta: "#ae89fe"
    cyan: "#708387"
    white: "#d5d5d0"
    brightBlack: "#626566"
    brightRed: "#ff7fac"
    brightGreen: "#c8ed71"
    brightYellow: "#ebdf86"
    brightBlue: "#75dff2"
    brightMagenta: "#ae89fe"
    brightCyan: "#b1c6ca"
    brightWhite: "#f9f9f4"

# Records, feel free to edit them
records:
  - delay: 1005
    content: "\e[?1034h$ "
  - delay: 1183
    content: m
  - delay: 267
    content: o
  - delay: 266
    content: 'n'
  - delay: 202
    content: g
  - delay: 485
    content: o
  - delay: 228
    content: c
  - delay: 196
    content: l
  - delay: 268
    content: i
  - delay: 685
    content: ' '
  - delay: 214
    content: c
  - delay: 221
    content: o
  - delay: 266
    content: 'n'
  - delay: 186
    content: f
  - delay: 177
    content: i
  - delay: 240
    content: g
  - delay: 695
    content: ' '
  - delay: 211
    content: '-'
  - delay: 220
    content: '-'
  - delay: 528
    content: s
  - delay: 212
    content: e
  - delay: 209
    content: r
  - delay: 257
    content: v
  - delay: 200
    content: i
  - delay: 98
    content: c
  - delay: 250
    content: e
  - delay: 714
    content: ' '
  - delay: 1243
    content: o
  - delay: 221
    content: p
  - delay: 184
    content: s
  - delay: 187
    content: '-'
  - delay: 285
    content: m
  - delay: 165
    content: a
  - delay: 311
    content: 'n'
  - delay: 134
    content: a
  - delay: 247
    content: g
  - delay: 104
    content: e
  - delay: 222
    content: r
  - delay: 656
    content: "\r\n"
  - delay: 58
    content: "\e[0G\e[2K\e[1;92m? \e[0m\e[1;99mURL to Access Ops Manage: \e[0m\e[36m[? for help]\e[0m \e[?25l\e7\e[999;999f\e[6n\e8\e[?25h\e[6n"
  - delay: 1585
    content: h
  - delay: 325
    content: t
  - delay: 202
    content: t
  - delay: 338
    content: p
  - delay: 803
    content: ':'
  - delay: 373
    content: /
  - delay: 262
    content: /
  - delay: 913
    content: l
  - delay: 290
    content: o
  - delay: 531
    content: c
  - delay: 193
    content: a
  - delay: 148
    content: l
  - delay: 289
    content: h
  - delay: 261
    content: o
  - delay: 151
    content: s
  - delay: 251
    content: t
  - delay: 1095
    content: ':'
  - delay: 657
    content: '9'
  - delay: 311
    content: '0'
  - delay: 868
    content: '8'
  - delay: 271
    content: '0'
  - delay: 1054
    content: /
  - delay: 743
    content: "\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1E\e[1F\e[0G\e[2K\e[1;92m? \e[0m\e[1;99mURL to Access Ops Manage: \e[0m\e[36mhttp://localhost:9080/\e[0m\r\n\e[0G\e[2K\e[1;92m? \e[0m\e[1;99mPublic API Key: \e[0m\e[36m[? for help]\e[0m \e[?25l\e7\e[999;999f\e[6n\e8\e[?25h\e[6n"
  - delay: 2813
    content: '1'
  - delay: 269
    content: '2'
  - delay: 249
    content: '3'
  - delay: 293
    content: '4'
  - delay: 569
    content: "\e[1D\e[1D\e[1D\e[1D\e[1E\e[1F\e[0G\e[2K\e[1;92m? \e[0m\e[1;99mPublic API Key: \e[0m\e[36m1234\e[0m\r\n\e[1;92m? \e[0m\e[1;99mPrivate API Key: \e[0m\e[36m[? for help]\e[0m \e[?25l\e7\e[999;999f\e[6n\e8\e[?25h\e[6n"
  - delay: 829
    content: '*'
  - delay: 287
    content: '*'
  - delay: 270
    content: '*'
  - delay: 1136
    content: '*'
  - delay: 442
    content: '*'
  - delay: 580
    content: '*'
  - delay: 332
    content: '*'
  - delay: 248
    content: '*'
  - delay: 475
    content: "\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1D\e[1E\e[0G\e[2K\e[1;92m? \e[0m\e[1;99mProject ID [optional]: \e[0m\e[36m[? for help]\e[0m \e[?25l\e7\e[999;999f\e[6n\e8\e[?25h\e[6n"
  - delay: 6327
    content: "\e[1E\e[1F\e[0G\e[2K\e[1;92m? \e[0m\e[1;99mProject ID [optional]: \e[0m\e[36m\e[0m\r\n"
  - delay: 9
    content: '$ '
  - delay: 1813
    content: "\r\n"
